user apearing in home
pcamelofreitas/project-base pull request #4
Opened 2022-06-03 22:29 UTC by pcamelofreitas

2022-06-06 10:58 UTC, victormarques-ia requested changes

2022-06-06 10:58 UTC, victormarques-ia commented on lib/src/home/presentation/dummies/home_screen.dart
> +              return ListView(
Aqui pode ser utilizado o ListView.builder, ele meio que já faz uma iteração retornando o index e ai vc pode acessar o item da lista a partir dele.

```
ListView.builder(
        itemCount: userList.length,
        itemBuilder: (BuildContext context,int index){
          return ListTile(
            leading: Icon(Icons.list),
            title:Text("List item ${userList[index]}")
            );
        }
        ),
```

2022-06-06 10:58 UTC, victormarques-ia commented on lib/src/home/data/repositories/home_repository.dart
> +    Result responseTwo = await _apiRepository.get(url: 'api/users?page=2');
Aqui não poderia fazer meio que uma paginação na tela, que quando fosse necessário, chamaria essa mesma requisição passando esse page=2 como um query paramater do Dio ?

2022-06-06 19:37 UTC, pcamelofreitas commented on lib/src/home/data/repositories/home_repository.dart
> +    Result responseTwo = await _apiRepository.get(url: 'api/users?page=2');
Fiquei um pouco na dúvida de como fazer a paginação na tela acabei fazendo com dois FloatingButton mesmo, talvez aja uma forma melhor, mas faz mais sentindo fazer a chamada de cada página mesmo.

2022-06-06 21:02 UTC, victormarques-ia requested changes

2022-06-06 21:02 UTC, victormarques-ia commented on lib/src/home/data/repositories/home_repository.dart
> +    // Result responseTwo = await _apiRepository.get(url: 'api/users?page=2');
Perfeito, agr só remover esse coment

2022-06-07 01:54 UTC, victormarques-ia approved these changes

2022-06-07 01:54 UTC, merged